import type { Carrier, Order } from './types'

export const SEED_CARRIERS: Carrier[] = [
  { id: 'c1', name: 'FastFreight LLC', mcNumber: 'MC-123456', phone: '312-555-0101', rating: 5 },
  { id: 'c2', name: 'TransAmerica Logistics', mcNumber: 'MC-234567', phone: '773-555-0202', rating: 4 },
  { id: 'c3', name: 'Midwest Express', mcNumber: 'MC-345678', phone: '847-555-0303', rating: 4 },
  { id: 'c4', name: 'Southern Star Transport', mcNumber: 'MC-456789', phone: '214-555-0404', rating: 3 },
  { id: 'c5', name: 'Pacific Route Carriers', mcNumber: 'MC-567890', phone: '213-555-0505', rating: 5 },
  { id: 'c6', name: 'Great Plains Freight', mcNumber: 'MC-678901', phone: '402-555-0606', rating: 4 },
  { id: 'c7', name: 'Rocky Mountain Haul', mcNumber: 'MC-789012', phone: '303-555-0707', rating: 3 },
  { id: 'c8', name: 'Atlantic Coast Lines', mcNumber: 'MC-890123', phone: '617-555-0808', rating: 5 },
  { id: 'c9', name: 'Lone Star Trucking', mcNumber: 'MC-901234', phone: '512-555-0909', rating: 4 },
  { id: 'c10', name: 'NorthStar Freight', mcNumber: 'MC-012345', phone: '651-555-1010', rating: 4 },
  { id: 'c11', name: 'Sun Belt Carriers', mcNumber: 'MC-112233', phone: '504-555-1111', rating: 3 },
  { id: 'c12', name: 'Blue Ridge Transport', mcNumber: 'MC-223344', phone: '704-555-1212', rating: 5 },
  { id: 'c13', name: 'Delta Freight Solutions', mcNumber: 'MC-334455', phone: '901-555-1313', rating: 4 },
  { id: 'c14', name: 'Cascade Logistics', mcNumber: 'MC-445566', phone: '206-555-1414', rating: 3 },
  { id: 'c15', name: 'Gulf Coast Freight', mcNumber: 'MC-556677', phone: '713-555-1515', rating: 4 },
]

function daysAgo(n: number, hourOffset = 0): string {
  const d = new Date()
  d.setDate(d.getDate() - n)
  d.setHours(hourOffset, 0, 0, 0)
  return d.toISOString()
}

export const SEED_ORDERS: Order[] = [
  {
    id: 'o1',
    referenceNumber: 'ORD-2024-0001',
    status: 'delivered',
    clientName: 'Acme Corp',
    carrier: SEED_CARRIERS[0],
    equipmentType: 'dry_van',
    loadType: 'ftl',
    weight: 32000,
    rate: 2450.0,
    notes: 'Handle with care',
    createdAt: daysAgo(55),
    updatedAt: daysAgo(50),
    stops: [
      { id: 's1', type: 'pick_up', order: 0, address: { city: 'Chicago', state: 'IL', zip: '60601' }, locationName: 'Chicago Warehouse', appointmentType: 'fixed', appointmentDate: daysAgo(53, 8) },
      { id: 's2', type: 'drop_off', order: 1, address: { city: 'Memphis', state: 'TN', zip: '38101' }, locationName: 'Memphis Distribution', appointmentType: 'fixed', appointmentDate: daysAgo(52, 14) },
    ],
    statusHistory: [
      { from: null, to: 'pending', changedAt: daysAgo(55), note: 'Order created' },
      { from: 'pending', to: 'in_transit', changedAt: daysAgo(53, 9) },
      { from: 'in_transit', to: 'delivered', changedAt: daysAgo(52, 15), note: 'Delivered on time' },
    ],
  },
  {
    id: 'o2',
    referenceNumber: 'ORD-2024-0002',
    status: 'in_transit',
    clientName: 'Global Industries',
    carrier: SEED_CARRIERS[1],
    equipmentType: 'reefer',
    loadType: 'ftl',
    weight: 28000,
    rate: 3200.0,
    notes: 'Temperature sensitive: keep at 34°F',
    createdAt: daysAgo(10),
    updatedAt: daysAgo(3),
    stops: [
      { id: 's3', type: 'pick_up', order: 0, address: { city: 'Dallas', state: 'TX', zip: '75201' }, locationName: 'DFW Cold Storage', appointmentType: 'fixed', appointmentDate: daysAgo(8, 7) },
      { id: 's4', type: 'stop', order: 1, address: { city: 'Oklahoma City', state: 'OK', zip: '73101' }, appointmentType: 'window', appointmentDate: daysAgo(7, 12) },
      { id: 's5', type: 'drop_off', order: 2, address: { city: 'Kansas City', state: 'MO', zip: '64101' }, locationName: 'KC Food Hub', appointmentType: 'fixed', appointmentDate: daysAgo(6, 9) },
    ],
    statusHistory: [
      { from: null, to: 'pending', changedAt: daysAgo(10) },
      { from: 'pending', to: 'in_transit', changedAt: daysAgo(8, 8) },
    ],
  },
  {
    id: 'o3',
    referenceNumber: 'ORD-2024-0003',
    status: 'pending',
    clientName: 'TechParts Inc',
    carrier: SEED_CARRIERS[2],
    equipmentType: 'flatbed',
    loadType: 'ftl',
    weight: 42000,
    rate: 1800.5,
    notes: '',
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
    stops: [
      { id: 's6', type: 'pick_up', order: 0, address: { city: 'Detroit', state: 'MI', zip: '48201' }, appointmentType: 'fixed', appointmentDate: daysAgo(1, 8) },
      { id: 's7', type: 'drop_off', order: 1, address: { city: 'Cleveland', state: 'OH', zip: '44101' }, appointmentType: 'fcfs', appointmentDate: daysAgo(0, 16) },
    ],
    statusHistory: [{ from: null, to: 'pending', changedAt: daysAgo(2) }],
  },
  {
    id: 'o4',
    referenceNumber: 'ORD-2024-0004',
    status: 'cancelled',
    clientName: 'Sunrise Foods',
    carrier: SEED_CARRIERS[3],
    equipmentType: 'reefer',
    loadType: 'ltl',
    weight: 12000,
    rate: 950.0,
    notes: 'Perishable goods',
    createdAt: daysAgo(30),
    updatedAt: daysAgo(28),
    stops: [
      { id: 's8', type: 'pick_up', order: 0, address: { city: 'Miami', state: 'FL', zip: '33101' }, appointmentType: 'fixed', appointmentDate: daysAgo(29, 6) },
      { id: 's9', type: 'drop_off', order: 1, address: { city: 'Atlanta', state: 'GA', zip: '30301' }, appointmentType: 'window', appointmentDate: daysAgo(28, 10) },
    ],
    statusHistory: [
      { from: null, to: 'pending', changedAt: daysAgo(30) },
      { from: 'pending', to: 'cancelled', changedAt: daysAgo(28), note: 'Client request: shipment no longer needed' },
    ],
  },
  {
    id: 'o5',
    referenceNumber: 'ORD-2024-0005',
    status: 'delivered',
    clientName: 'BuildRight Construction',
    carrier: SEED_CARRIERS[4],
    equipmentType: 'flatbed',
    loadType: 'ftl',
    weight: 48000,
    rate: 3800.0,
    notes: 'Heavy equipment — pilot car required',
    createdAt: daysAgo(45),
    updatedAt: daysAgo(40),
    stops: [
      { id: 's10', type: 'pick_up', order: 0, address: { city: 'Los Angeles', state: 'CA', zip: '90001' }, appointmentType: 'fixed', appointmentDate: daysAgo(44, 7) },
      { id: 's11', type: 'stop', order: 1, address: { city: 'Phoenix', state: 'AZ', zip: '85001' }, appointmentType: 'fcfs', appointmentDate: daysAgo(43, 12) },
      { id: 's12', type: 'drop_off', order: 2, address: { city: 'Las Vegas', state: 'NV', zip: '89101' }, appointmentType: 'fixed', appointmentDate: daysAgo(42, 9) },
    ],
    statusHistory: [
      { from: null, to: 'pending', changedAt: daysAgo(45) },
      { from: 'pending', to: 'in_transit', changedAt: daysAgo(44, 8) },
      { from: 'in_transit', to: 'delivered', changedAt: daysAgo(42, 10) },
    ],
  },
  {
    id: 'o6',
    referenceNumber: 'ORD-2024-0006',
    status: 'pending',
    clientName: 'MedSupply Co',
    carrier: SEED_CARRIERS[5],
    equipmentType: 'reefer',
    loadType: 'ftl',
    weight: 8500,
    rate: 4200.0,
    notes: 'Medical supplies — priority delivery',
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
    stops: [
      { id: 's13', type: 'pick_up', order: 0, address: { city: 'Indianapolis', state: 'IN', zip: '46201' }, appointmentType: 'fixed', appointmentDate: daysAgo(0, 9) },
      { id: 's14', type: 'drop_off', order: 1, address: { city: 'Columbus', state: 'OH', zip: '43201' }, appointmentType: 'fixed', appointmentDate: daysAgo(0, 15) },
    ],
    statusHistory: [{ from: null, to: 'pending', changedAt: daysAgo(1) }],
  },
  {
    id: 'o7',
    referenceNumber: 'ORD-2024-0007',
    status: 'in_transit',
    clientName: 'AutoParts Direct',
    carrier: SEED_CARRIERS[6],
    equipmentType: 'dry_van',
    loadType: 'ltl',
    weight: 15000,
    rate: 1350.0,
    notes: '',
    createdAt: daysAgo(7),
    updatedAt: daysAgo(5),
    stops: [
      { id: 's15', type: 'pick_up', order: 0, address: { city: 'Denver', state: 'CO', zip: '80201' }, appointmentType: 'window', appointmentDate: daysAgo(6, 8) },
      { id: 's16', type: 'stop', order: 1, address: { city: 'Albuquerque', state: 'NM', zip: '87101' }, appointmentType: 'fcfs', appointmentDate: daysAgo(5, 14) },
      { id: 's17', type: 'drop_off', order: 2, address: { city: 'Tucson', state: 'AZ', zip: '85701' }, appointmentType: 'fixed', appointmentDate: daysAgo(4, 10) },
    ],
    statusHistory: [
      { from: null, to: 'pending', changedAt: daysAgo(7) },
      { from: 'pending', to: 'in_transit', changedAt: daysAgo(6, 9) },
    ],
  },
  {
    id: 'o8',
    referenceNumber: 'ORD-2024-0008',
    status: 'delivered',
    clientName: 'HomeGoods Plus',
    carrier: SEED_CARRIERS[7],
    equipmentType: 'dry_van',
    loadType: 'ftl',
    weight: 38000,
    rate: 2100.0,
    notes: 'Fragile items',
    createdAt: daysAgo(25),
    updatedAt: daysAgo(20),
    stops: [
      { id: 's18', type: 'pick_up', order: 0, address: { city: 'Boston', state: 'MA', zip: '02101' }, appointmentType: 'fixed', appointmentDate: daysAgo(24, 7) },
      { id: 's19', type: 'drop_off', order: 1, address: { city: 'New York', state: 'NY', zip: '10001' }, appointmentType: 'fixed', appointmentDate: daysAgo(23, 14) },
    ],
    statusHistory: [
      { from: null, to: 'pending', changedAt: daysAgo(25) },
      { from: 'pending', to: 'in_transit', changedAt: daysAgo(24, 8) },
      { from: 'in_transit', to: 'delivered', changedAt: daysAgo(23, 15), note: 'Signature obtained' },
    ],
  },
  {
    id: 'o9',
    referenceNumber: 'ORD-2024-0009',
    status: 'pending',
    clientName: 'FreshProduce LLC',
    carrier: SEED_CARRIERS[8],
    equipmentType: 'reefer',
    loadType: 'ftl',
    weight: 22000,
    rate: 2750.0,
    notes: 'Keep at 38°F',
    createdAt: daysAgo(3),
    updatedAt: daysAgo(3),
    stops: [
      { id: 's20', type: 'pick_up', order: 0, address: { city: 'San Antonio', state: 'TX', zip: '78201' }, appointmentType: 'fixed', appointmentDate: daysAgo(2, 5) },
      { id: 's21', type: 'drop_off', order: 1, address: { city: 'Houston', state: 'TX', zip: '77001' }, appointmentType: 'window', appointmentDate: daysAgo(1, 11) },
    ],
    statusHistory: [{ from: null, to: 'pending', changedAt: daysAgo(3) }],
  },
  {
    id: 'o10',
    referenceNumber: 'ORD-2024-0010',
    status: 'in_transit',
    clientName: 'SteelWorks Corp',
    carrier: SEED_CARRIERS[9],
    equipmentType: 'flatbed',
    loadType: 'ftl',
    weight: 65000,
    rate: 5200.0,
    notes: 'Steel coils — tarps required',
    createdAt: daysAgo(12),
    updatedAt: daysAgo(9),
    stops: [
      { id: 's22', type: 'pick_up', order: 0, address: { city: 'Minneapolis', state: 'MN', zip: '55401' }, appointmentType: 'fixed', appointmentDate: daysAgo(11, 7) },
      { id: 's23', type: 'stop', order: 1, address: { city: 'Milwaukee', state: 'WI', zip: '53201' }, appointmentType: 'window', appointmentDate: daysAgo(10, 12) },
      { id: 's24', type: 'stop', order: 2, address: { city: 'Chicago', state: 'IL', zip: '60601' }, appointmentType: 'fcfs', appointmentDate: daysAgo(9, 8) },
      { id: 's25', type: 'drop_off', order: 3, address: { city: 'Gary', state: 'IN', zip: '46401' }, appointmentType: 'fixed', appointmentDate: daysAgo(8, 14) },
    ],
    statusHistory: [
      { from: null, to: 'pending', changedAt: daysAgo(12) },
      { from: 'pending', to: 'in_transit', changedAt: daysAgo(11, 8) },
    ],
  },
  {
    id: 'o11',
    referenceNumber: 'ORD-2024-0011',
    status: 'delivered',
    clientName: 'RetailChain Co',
    carrier: SEED_CARRIERS[10],
    equipmentType: 'dry_van',
    loadType: 'ltl',
    weight: 18000,
    rate: 1600.0,
    notes: '',
    createdAt: daysAgo(40),
    updatedAt: daysAgo(35),
    stops: [
      { id: 's26', type: 'pick_up', order: 0, address: { city: 'New Orleans', state: 'LA', zip: '70112' }, appointmentType: 'fixed', appointmentDate: daysAgo(39, 8) },
      { id: 's27', type: 'drop_off', order: 1, address: { city: 'Jackson', state: 'MS', zip: '39201' }, appointmentType: 'fcfs', appointmentDate: daysAgo(38, 14) },
    ],
    statusHistory: [
      { from: null, to: 'pending', changedAt: daysAgo(40) },
      { from: 'pending', to: 'in_transit', changedAt: daysAgo(39, 9) },
      { from: 'in_transit', to: 'delivered', changedAt: daysAgo(38, 15) },
    ],
  },
  {
    id: 'o12',
    referenceNumber: 'ORD-2024-0012',
    status: 'cancelled',
    clientName: 'PhotonElectronics',
    carrier: SEED_CARRIERS[11],
    equipmentType: 'dry_van',
    loadType: 'ftl',
    weight: 9500,
    rate: 1900.0,
    notes: 'Electronics — no rough handling',
    createdAt: daysAgo(20),
    updatedAt: daysAgo(18),
    stops: [
      { id: 's28', type: 'pick_up', order: 0, address: { city: 'Charlotte', state: 'NC', zip: '28201' }, appointmentType: 'fixed', appointmentDate: daysAgo(19, 9) },
      { id: 's29', type: 'drop_off', order: 1, address: { city: 'Raleigh', state: 'NC', zip: '27601' }, appointmentType: 'fixed', appointmentDate: daysAgo(18, 13) },
    ],
    statusHistory: [
      { from: null, to: 'pending', changedAt: daysAgo(20) },
      { from: 'pending', to: 'cancelled', changedAt: daysAgo(18), note: 'Route changed by client' },
    ],
  },
  {
    id: 'o13',
    referenceNumber: 'ORD-2024-0013',
    status: 'pending',
    clientName: 'GardenWorld',
    carrier: SEED_CARRIERS[12],
    equipmentType: 'flatbed',
    loadType: 'ltl',
    weight: 25000,
    rate: 2200.0,
    notes: 'Outdoor furniture — weather protection needed',
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
    stops: [
      { id: 's30', type: 'pick_up', order: 0, address: { city: 'Memphis', state: 'TN', zip: '38101' }, appointmentType: 'window', appointmentDate: daysAgo(0, 8) },
      { id: 's31', type: 'drop_off', order: 1, address: { city: 'Nashville', state: 'TN', zip: '37201' }, appointmentType: 'fixed', appointmentDate: daysAgo(0, 14) },
    ],
    statusHistory: [{ from: null, to: 'pending', changedAt: daysAgo(1) }],
  },
  {
    id: 'o14',
    referenceNumber: 'ORD-2024-0014',
    status: 'in_transit',
    clientName: 'TechDistrib LLC',
    carrier: SEED_CARRIERS[13],
    equipmentType: 'dry_van',
    loadType: 'ftl',
    weight: 14000,
    rate: 3100.0,
    notes: '',
    createdAt: daysAgo(8),
    updatedAt: daysAgo(6),
    stops: [
      { id: 's32', type: 'pick_up', order: 0, address: { city: 'Seattle', state: 'WA', zip: '98101' }, appointmentType: 'fixed', appointmentDate: daysAgo(7, 8) },
      { id: 's33', type: 'stop', order: 1, address: { city: 'Portland', state: 'OR', zip: '97201' }, appointmentType: 'fcfs', appointmentDate: daysAgo(6, 12) },
      { id: 's34', type: 'drop_off', order: 2, address: { city: 'Sacramento', state: 'CA', zip: '95814' }, appointmentType: 'fixed', appointmentDate: daysAgo(5, 10) },
    ],
    statusHistory: [
      { from: null, to: 'pending', changedAt: daysAgo(8) },
      { from: 'pending', to: 'in_transit', changedAt: daysAgo(7, 9) },
    ],
  },
  {
    id: 'o15',
    referenceNumber: 'ORD-2024-0015',
    status: 'delivered',
    clientName: 'Acme Corp',
    carrier: SEED_CARRIERS[14],
    equipmentType: 'reefer',
    loadType: 'ftl',
    weight: 31000,
    rate: 4800.0,
    notes: 'Temperature monitoring required',
    createdAt: daysAgo(35),
    updatedAt: daysAgo(30),
    stops: [
      { id: 's35', type: 'pick_up', order: 0, address: { city: 'Houston', state: 'TX', zip: '77001' }, appointmentType: 'fixed', appointmentDate: daysAgo(34, 6) },
      { id: 's36', type: 'stop', order: 1, address: { city: 'Baton Rouge', state: 'LA', zip: '70801' }, appointmentType: 'window', appointmentDate: daysAgo(33, 11) },
      { id: 's37', type: 'drop_off', order: 2, address: { city: 'New Orleans', state: 'LA', zip: '70112' }, appointmentType: 'fixed', appointmentDate: daysAgo(32, 9) },
    ],
    statusHistory: [
      { from: null, to: 'pending', changedAt: daysAgo(35) },
      { from: 'pending', to: 'in_transit', changedAt: daysAgo(34, 7) },
      { from: 'in_transit', to: 'delivered', changedAt: daysAgo(32, 10), note: 'Delivered — temp log attached' },
    ],
  },
]
